version: '3'
services:
  faq-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/faq-db
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
